#!/usr/bin/env bash
# bootstrap.sh — Initialize the skill-update nexus-autoloop runner.
# Idempotent: safe to re-run. Use --reset to wipe state and restart.

set -euo pipefail

LOOP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_ROOT="$(cd "${LOOP_DIR}/../.." && pwd)"
STATE_DIR="${LOOP_DIR}/state"
REPORTS_DIR="${LOOP_DIR}/reports"
BATCHES_DIR="${LOOP_DIR}/batches"

mkdir -p "${STATE_DIR}" "${REPORTS_DIR}" "${BATCHES_DIR}"

# Portable SHA-256 hash (BSD/GNU compatible)
sha256_hash() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$@"
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$@"
  else
    echo "[ERROR] sha256sum/shasum not found" >&2
    return 1
  fi
}

reset_mode=false
for arg in "$@"; do
  case "${arg}" in
    --reset) reset_mode=true ;;
    *) echo "[bootstrap] unknown arg: ${arg}" >&2; exit 64 ;;
  esac
done

if "${reset_mode}"; then
  echo "[bootstrap] --reset: clearing state, reports, batches"
  rm -f "${STATE_DIR}"/* "${REPORTS_DIR}"/* "${BATCHES_DIR}"/*
fi

# --- 1. Generate skills-pending.txt -----------------------------------------
PENDING="${STATE_DIR}/skills-pending.txt"
if [[ ! -s "${PENDING}" ]]; then
  echo "[bootstrap] discovering skills under ${SKILLS_ROOT}"
  find "${SKILLS_ROOT}" -mindepth 2 -maxdepth 2 -name SKILL.md -type f \
    | sed -E "s|${SKILLS_ROOT}/([^/]+)/SKILL\.md|\1|" \
    | grep -Ev '^(_common|_templates|\.agents|\.loops)$' \
    | sort -u > "${PENDING}"
  count=$(wc -l <"${PENDING}" | tr -d ' ')
  echo "[bootstrap] ${count} skills enqueued"
fi

# --- 2. Initialize state.env ------------------------------------------------
STATE_ENV="${STATE_DIR}/state.env"
if [[ ! -f "${STATE_ENV}" ]]; then
  cat > "${STATE_ENV}.tmp" <<EOF
# Auto-generated by bootstrap.sh — do not hand-edit while loop is running.
NEXT_ITERATION=1
LAST_STATUS=READY
LAST_RUN_AT=
SKILLS_REMAINING=$(wc -l <"${PENDING}" | tr -d ' ')
SKILLS_TOTAL=$(wc -l <"${PENDING}" | tr -d ' ')
BATCH_SIZE=5
EOF
  mv -- "${STATE_ENV}.tmp" "${STATE_ENV}"
  echo "[bootstrap] state.env initialised"
fi

# --- 3. Initial state.env checksum ------------------------------------------
sha256_hash "${STATE_ENV}" | awk '{print $1}' > "${STATE_DIR}/state.env.sha256.tmp"
mv -- "${STATE_DIR}/state.env.sha256.tmp" "${STATE_DIR}/state.env.sha256"

# --- 4. Initialize progress.md ----------------------------------------------
PROGRESS="${LOOP_DIR}/progress.md"
if [[ ! -f "${PROGRESS}" ]]; then
  cat > "${PROGRESS}" <<'EOF'
# Skill-Update Loop Progress

| Iter | Started | Finished | Batch | Skills processed | Status | Notes |
|------|---------|----------|-------|------------------|--------|-------|
EOF
  echo "[bootstrap] progress.md initialised"
fi

# --- 5. Initialize report files ---------------------------------------------
[[ -f "${REPORTS_DIR}/audit.md"        ]] || printf '# Skill Audit Report\n\n' > "${REPORTS_DIR}/audit.md"
[[ -f "${REPORTS_DIR}/improvements.md" ]] || printf '# Improvement Proposals\n\n' > "${REPORTS_DIR}/improvements.md"
[[ -f "${REPORTS_DIR}/capabilities-drift.md" ]] || printf '# CAPABILITIES_SUMMARY Drift\n\n' > "${REPORTS_DIR}/capabilities-drift.md"

# --- 6. Pre-flight summary --------------------------------------------------
echo "[bootstrap] ready"
echo "  loop_dir   : ${LOOP_DIR}"
echo "  skills_root: ${SKILLS_ROOT}"
echo "  pending    : $(wc -l <"${PENDING}" | tr -d ' ')"
echo "  state.env  : ${STATE_ENV}"
echo "  next       : run-loop.sh"
